services:
  web:
    container_name: ${CONTAINER_PREFIX}_nginx
    image: nginx:latest
    volumes:
      - ./www/:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs:/var/log/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
  php:
    container_name: ${CONTAINER_PREFIX}_fpm
    build:
      context: .
      dockerfile: ./config/php/PHP.Dockerfile
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql
  mysql:
    container_name: ${CONTAINER_PREFIX}_db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
volumes:
  mysql:
    name: ${CONTAINER_PREFIX}_db